### ISSUE TITLE
speed up tests

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#187]
They're slow -

**Comment by lukechurch** [comment]
Really really slow, I agree.

The problem is the lack of the ability to do the startup and tear down after all the tests, rather than after each test so right now we have to cycle the Analysis Server, which is really expensive. I don't really like the counting hack, it seems like I'm likely to make mistakes. Hence the slowness.

**Comment by devoncarew** [comment]
There may be a way using `group`s - I'll investigate.

**Comment by devoncarew** [comment]
The new `test` package has a dependency on the `analyzer`. This is going to cause a lot of version lock issues for us, esp. as we'll need to be on bleeding edge versions of the analyzer.
