### ISSUE TITLE
unit / integration test for code completion

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-services#93]

**Comment by lukechurch** [comment]
Yeah, i have a bunch of these locally that I'm running - they're a bit tricky to get into the repo because of their dependency on paths to infrastructure e.g. package roots, which are local.

They need turning into parameters of the tests. Do you have a defined list of where this stuff lives on Drone IO and what version of the VM it's running?

**Comment by devoncarew** [comment]
I suspect our readme (https://github.com/dart-lang/dart-services/blob/master/README.md) for setting up the server is out of date. Can you create some simple steps in a wiki or something? That'll help me figure out what we need for the buildbot.

**Comment by devoncarew** [comment]
The test and benchmarks are initiated from here: https://github.com/dart-lang/dart-services/blob/master/tool/travis.sh.

**Comment by lukechurch** [comment]
A simple test is now in. Will expand the set over time.
